In [80]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

In [81]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [82]:
import math
median_test_score=math.floor(df['test_score(out of 10)'].mean())
median_test_score


7

In [83]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [84]:
# prompt: Using dataframe df: experience column fill NaN with median but mapping first

# Create a mapping dictionary for experience levels
experience_mapping = {
    'five':5, 'two':2, 'seven':7, 'three':3, 'ten':10, 'eleven':11,
    0: 0,  # Example mapping, replace with your actual mappings
    # Add more experience levels and their corresponding numerical values
}

# Map the experience column using the mapping dictionary
df['experience'] = df['experience'].map(experience_mapping)

# Calculate the median of the experience column
median_experience = df['experience'].median()
median_experience
# Fill NaN values in the experience column with the calculated median
df['experience']=df['experience'].fillna(median_experience)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [87]:
model = LinearRegression()
model.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [89]:
model.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46799.52198459])

In [90]:
model.intercept_

12371.698190958909

In [91]:
model.coef_

array([2874.43853793, 1225.36778341, 2941.77277785])

In [92]:
# y= [m1x1 + m2x2 + .....] + C
2*2874.43853793 + 9*1225.36778341 + 6*2941.77277785+12371.698190958909

46799.52198460891

In [93]:
model.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88536.36625871])

In [94]:
# y= [m1x1 + m2x2 + .....] + C
12*2874.43853793 + 10*1225.36778341 + 10*2941.77277785+12371.698190958909

88536.36625871892